### ISSUE TITLE
Links dos projetos de conclusão

### ISSUE THREAD

**Issue by gabbianiiii** [training-center/sap-study-group#9]
Coloquem os links dos seus repositórios ref. ao projeto de conclusão. Mais informações [aqui](https://github.com/training-center/sap-study-group/blob/master/material/challenges/projects.md).

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by gabbianiiii** [comment]
Por hora podemos fechar essa issue. Assim que houver mais algum blog a ser incluido, eu reabro.
